### ISSUE TITLE
Nothing about other bots in docs

### ISSUE THREAD

**Issue by itJunky** [pedrohml/smartbot#2]
In help or README.md i see tiny help without any bots like nasa or google images. How can i use it?

**Comment by pedrohml** [comment]
I am improving the documentation. 
For now, when you execute smartbot_full.py you will run a bot with all that behaviours listed in README.
Fo example:

In telegram:
```
/gimage red fox
/nasa
```

In slack:
```
_gimage red fox
_nasa
```

If you are interested in a bot with friendly communication you can create a **.cfg* file like [template](https://github.com/pedrohml/smartbot/blob/master/config/smartbot_full.cfg) and use like that:

For google image:
```
@botname send red fox
```

For nasa:
```
@botname nasa
```

A more complete documentation is coming

**Comment by itJunky** [comment]
thanks
